name: CICD for Serverless Application
run-name: ${{ github.actor }} is doing CICD for Serverless Application

on:
  push:
    branches: [ main, "*" ]

jobs:
  pre-deploystep1: #job name(can be any name,which will appear on the github action page/pipeline)
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is automatically triggerd by a ${{ github.event_name }} event."

  install-dependenciesstep2:
    runs-on: ubuntu-latest
    needs: pre-deploystep1
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Run installation of dependencies command
        run: npm install

  unit-testingstep3:
    runs-on: ubuntu-latest
    needs: install-dependenciesstep2
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Run installation of dependencies command
        run: npm install
      - name: Run unit testing command
        run: npm run test

  deploystep4:
    runs-on: ubuntu-latest
    needs: unit-testingstep3
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Serverless deploy to AWS
        uses: serverless/github-action@master
        with:
          args: deploystep4
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #Parameter:
         # Name: pglim360parameter
          #Type: String
          #Value: file
          #Version: 2
          #LastModifiedDate: 1692100383.712
          #ARN: arn:aws:ssm:ap-southeast-1:255945442255:parameter/pglim360parameter
          #DataType: text
  Snykstep5:
     - name: run Snyk Open Source Test
        run: snyk test
      - name: run Snyk Code Test
        run: snyk code test
     # - name: Set up Node 14
      #  uses: actions/setup-node@v3
     #   with:
     #   node-version: 14
      #- name: install Snyk CLI
     #   run: npm install -g snyk
